#!/bin/bash
VER="{{version}}"

export PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export LANG=C
export LC_CTYPE=C
export LC_ALL=C

cd $(dirname $0)

echo > /tmp/pdp_err.txt
cp -f ../Resources/script.sh /tmp/pdp_script.sh
osascript -e 'do shell script "/bin/bash /tmp/pdp_script.sh" with prompt "PD Patcher v'"$VER"'" with administrator privileges' && {
    afplay /System/Library/Sounds/Glass.aiff &
    osascript -e 'display alert "PD Patcher" message "Compelete!"'
} || {
    err=`cat /tmp/pdp_err.txt`
    afplay /System/Library/Sounds/Submarine.aiff &
    [ -n "$err" ] && {
        osascript -e 'display alert "PD Patcher" message "'"$err"'"'
    } || {
        osascript -e 'display alert "PD Patcher" message "Failed: Permission denied"'
    }
}
rm -f /tmp/pdp_script.sh /tmp/pdp_err.txt
